//! Code scaffold generation from YAML manifest.
//!
//! `vil generate handler <name> --from <yaml>` → typed Rust handler
//! `vil generate script <name> --runtime lua --from <yaml>` → script template

use colored::*;
use std::path::Path;
use vil_cli_core::manifest::WorkflowManifest;

/// Generate a Rust handler scaffold from a YAML manifest.
pub fn generate_handler(name: &str, from: &str, output_dir: &str) -> Result<(), String> {
    let manifest = WorkflowManifest::from_file(from)?;

    // Find the node or task that references this handler
    let (input_msg, output_msg, state_access, is_async) = find_handler_context(&manifest, name)?;

    let fn_name = name.replace('-', "_");
    let input_type = input_msg.unwrap_or_else(|| "serde_json::Value".into());
    let output_type = output_msg.unwrap_or_else(|| "serde_json::Value".into());
    let state_param = match state_access.as_deref() {
        Some("read") => "\n    _state: &ServiceState,",
        Some("read_write") => "\n    _state: &mut ServiceState,",
        _ => "",
    };
    let async_kw = if is_async { "async " } else { "" };

    let code = format!(
        r#"//! Handler: {name}
//! Generated by: vil generate handler {name} --from {from}
//! Input:  {input_type}
//! Output: {output_type}

use vil_server::prelude::*;

pub {async_kw}fn {fn_name}(
    input: {input_type},{state_param}
    _ctx: &HandlerContext,
) -> Result<{output_type}, VilError> {{
    // TODO: Implement handler logic
    //
    // Available:
    //   input  — typed request payload
    //   _ctx   — request context (trace_id, request_id, metrics)
    //   _state — service state (if state_access is read or read_write)
    //
    // Return Ok(output) or Err(VilError::...)

    todo!("Implement {fn_name}")
}}
"#,
        name = name,
        from = from,
        fn_name = fn_name,
        input_type = input_type,
        output_type = output_type,
        state_param = state_param,
        async_kw = async_kw,
    );

    // Write to output directory
    let dir = Path::new(output_dir);
    std::fs::create_dir_all(dir)
        .map_err(|e| format!("Failed to create directory '{}': {}", output_dir, e))?;

    let file_path = dir.join(format!("{}.rs", fn_name));
    std::fs::write(&file_path, &code)
        .map_err(|e| format!("Failed to write '{}': {}", file_path.display(), e))?;

    println!(
        "{} Generated handler: {}",
        "OK".green().bold(),
        file_path.display()
    );
    println!(
        "   fn {}({}) -> Result<{}, VilError>",
        fn_name, input_type, output_type
    );

    Ok(())
}

/// Generate a script template from a YAML manifest.
pub fn generate_script(
    name: &str,
    runtime: &str,
    from: &str,
    output_dir: &str,
) -> Result<(), String> {
    let manifest = WorkflowManifest::from_file(from)?;
    let (input_msg, output_msg, _, _) =
        find_handler_context(&manifest, name).unwrap_or((None, None, None, true));

    let input_type = input_msg.unwrap_or_else(|| "object".into());
    let output_type = output_msg.unwrap_or_else(|| "object".into());

    let (ext, code) = match runtime {
        "lua" => (
            "lua",
            format!(
                r#"-- Script: {name}
-- Generated by: vil generate script {name} --runtime lua --from {from}
-- Input type:  {input_type}
-- Output type: {output_type}

-- `input` is a global table matching the input message type
-- `ctx` provides: ctx.log(level, msg), ctx.request_id, ctx.trace_id

local out = {{}}

-- TODO: Implement script logic
out.result = input

ctx.log("info", "processed request " .. tostring(ctx.request_id))

return out
"#,
                name = name,
                from = from,
                input_type = input_type,
                output_type = output_type,
            ),
        ),
        "js" => (
            "js",
            format!(
                r#"// Script: {name}
// Generated by: vil generate script {name} --runtime js --from {from}
// Input type:  {input_type}
// Output type: {output_type}

// `input` is a global object matching the input message type
// `ctx` provides: ctx.log(level, msg), ctx.requestId, ctx.traceId

const out = {{}};

// TODO: Implement script logic
out.result = input;

ctx.log("info", `processed request ${{ctx.requestId}}`);

return out;
"#,
                name = name,
                from = from,
                input_type = input_type,
                output_type = output_type,
            ),
        ),
        "wasm" => (
            "rs",
            format!(
                r#"//! WASM module: {name}
//! Generated by: vil generate script {name} --runtime wasm --from {from}
//! Compile: cargo build --target wasm32-unknown-unknown --release

#![no_std]

#[no_mangle]
pub extern "C" fn {fn_name}(input_ptr: i32, input_len: i32) -> i32 {{
    // Input: read from linear memory at offset input_ptr, length input_len
    // Output: write to linear memory at offset 1024, return output length
    //
    // TODO: Implement WASM function logic

    0 // return output length
}}
"#,
                name = name,
                from = from,
                fn_name = name.replace('-', "_"),
            ),
        ),
        other => {
            return Err(format!(
                "Unknown runtime '{}'. Supported: lua, js, wasm",
                other
            ))
        }
    };

    let dir = Path::new(output_dir);
    std::fs::create_dir_all(dir)
        .map_err(|e| format!("Failed to create directory '{}': {}", output_dir, e))?;

    let file_path = dir.join(format!("{}.{}", name.replace('-', "_"), ext));
    std::fs::write(&file_path, &code)
        .map_err(|e| format!("Failed to write '{}': {}", file_path.display(), e))?;

    println!(
        "{} Generated {} script: {}",
        "OK".green().bold(),
        runtime,
        file_path.display()
    );

    Ok(())
}

/// Find the handler context (input/output message types, state_access, async)
/// by searching nodes and tasks in the manifest.
fn find_handler_context(
    manifest: &WorkflowManifest,
    handler_name: &str,
) -> Result<(Option<String>, Option<String>, Option<String>, bool), String> {
    // Search nodes for code.handler == handler_name
    for (_node_name, node) in &manifest.nodes {
        if let Some(code) = &node.code {
            if code.handler.as_deref() == Some(handler_name) {
                // Extract input/output from ports
                let input_msg = node
                    .ports
                    .values()
                    .find(|p| p.direction == "in")
                    .and_then(|p| p.message.clone());
                let output_msg = node
                    .ports
                    .values()
                    .find(|p| p.direction == "out")
                    .and_then(|p| p.message.clone());
                return Ok((
                    input_msg,
                    output_msg,
                    code.state_access.clone(),
                    code.r#async,
                ));
            }
        }
    }

    // Search workflow tasks for code.handler == handler_name
    for (_wf_name, wf) in &manifest.workflows {
        for task in &wf.tasks {
            if let Some(code) = &task.code {
                if code.handler.as_deref() == Some(handler_name) {
                    return Ok((None, None, code.state_access.clone(), code.r#async));
                }
            }
        }
    }

    // Not found — return defaults
    Ok((None, None, None, true))
}
