// =============================================================================
// vil deploy — One-command deployment to remote server
// =============================================================================
//
// Usage:
//   vil deploy --host 10.10.0.14 --user app --path /opt/my-app
//   vil deploy                  (uses .vil-deploy.toml)
//   vil deploy init             (create config)
//   vil deploy status           (check remote)
//   vil deploy rollback         (restore previous)

use colored::Colorize;
use std::fs;
use std::process::Command;

const CONFIG_FILE: &str = ".vil-deploy.toml";

#[derive(Debug)]
pub struct DeployConfig {
    pub host: String,
    pub user: String,
    pub path: String,
    pub service: String,
    pub binary: String,
    pub health_url: Option<String>,
}

pub fn run_deploy(
    action: &str,
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<(), String> {
    match action {
        "init" => deploy_init(host, user, path, service),
        "status" => deploy_status(host, user, path, service),
        "rollback" => deploy_rollback(host, user, path, service),
        "run" | "" => deploy_run(host, user, path, service),
        _ => Err(format!(
            "Unknown deploy action '{}'. Use: init, status, rollback",
            action
        )),
    }
}

fn deploy_init(
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<(), String> {
    let package = read_package_name().unwrap_or_else(|| "my-app".into());
    let host = host.unwrap_or("10.10.0.14");
    let user = user.unwrap_or("app");
    let default_path = format!("/opt/{}", &package);
    let path = path.unwrap_or(&default_path);
    let service = service.unwrap_or(&package);

    let content = format!(
        r#"# VIL Deploy Configuration
# Generated by: vil deploy init

[deploy]
host = "{host}"
user = "{user}"
path = "{path}"
service = "{service}"
binary = "{package}"

[deploy.health]
url = "http://localhost:8082/health"
timeout = 10

# [deploy.pre]
# commands = ["cargo test --test e2e"]

# [deploy.post]
# commands = ["systemctl status {service}"]
"#
    );

    fs::write(CONFIG_FILE, content).map_err(|e| e.to_string())?;
    println!("  {} {}", "Created".green().bold(), CONFIG_FILE);
    println!("  Edit the file, then run: {}", "vil deploy".cyan());
    Ok(())
}

fn deploy_run(
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<(), String> {
    let config = load_config(host, user, path, service)?;

    println!();
    println!("  {}", "╔══════════════════════════════════════╗".cyan());
    println!(
        "  {}  {} to {}@{}:{}  {}",
        "║".cyan(),
        "vil deploy".green().bold(),
        config.user,
        config.host,
        config.path,
        "║".cyan()
    );
    println!("  {}", "╚══════════════════════════════════════╝".cyan());
    println!();

    // Step 1: Build release
    println!("  {} Building release...", "1/4".yellow().bold());
    let build = Command::new("cargo")
        .args(["build", "--release"])
        .status()
        .map_err(|e| format!("cargo build: {}", e))?;
    if !build.success() {
        return Err("Release build failed".into());
    }
    println!("  {} Build complete", "✅".green());

    // Step 2: Backup old binary on remote
    println!("  {} Backing up on remote...", "2/4".yellow().bold());
    let _ = ssh(
        &config,
        &format!(
            "cp {}/{} {}/{}.bak 2>/dev/null || true",
            config.path, config.binary, config.path, config.binary
        ),
    );
    println!("  {} Backup done", "✅".green());

    // Step 3: Copy binary
    println!("  {} Uploading binary...", "3/4".yellow().bold());
    let binary_path = format!("target/release/{}", config.binary);
    if !std::path::Path::new(&binary_path).exists() {
        // Try with underscores
        let alt = format!("target/release/{}", config.binary.replace('-', "_"));
        if !std::path::Path::new(&alt).exists() {
            return Err(format!("Binary not found: {} or {}", binary_path, alt));
        }
        scp(&alt, &config)?;
    } else {
        scp(&binary_path, &config)?;
    }
    println!("  {} Upload complete", "✅".green());

    // Step 4: Restart service
    println!("  {} Restarting service...", "4/4".yellow().bold());
    ssh(&config, &format!("systemctl restart {}", config.service))?;

    // Health check
    if let Some(ref url) = config.health_url {
        println!("  {} Health check...", "→".dimmed());
        std::thread::sleep(std::time::Duration::from_secs(3));
        let check = ssh(&config, &format!("curl -sf {} || echo FAIL", url));
        match check {
            Ok(output) if !output.contains("FAIL") => {
                println!("  {} Healthy!", "✅".green());
            }
            _ => {
                println!(
                    "  {} Health check failed — consider rollback",
                    "⚠️".yellow()
                );
            }
        }
    }

    println!();
    println!(
        "  {} Deployed to {}@{}:{}",
        "🚀".green(),
        config.user,
        config.host,
        config.path
    );
    Ok(())
}

fn deploy_status(
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<(), String> {
    let config = load_config(host, user, path, service)?;

    println!(
        "  {} Checking {}@{}...",
        "→".dimmed(),
        config.user,
        config.host
    );

    // Service status
    let status = ssh(&config, &format!("systemctl is-active {}", config.service))?;
    let is_active = status.trim() == "active";
    if is_active {
        println!("  {} Service: {}", "✅".green(), "active".green());
    } else {
        println!("  {} Service: {}", "❌".red(), status.trim().red());
    }

    // Health check
    if let Some(ref url) = config.health_url {
        match ssh(&config, &format!("curl -sf {}", url)) {
            Ok(body) => println!("  {} Health: {}", "✅".green(), body.trim()),
            Err(_) => println!("  {} Health: unreachable", "❌".red()),
        }
    }

    // Binary info
    let ls = ssh(
        &config,
        &format!("ls -lh {}/{}", config.path, config.binary),
    );
    if let Ok(info) = ls {
        println!("  {} Binary: {}", "ℹ️ ".dimmed(), info.trim());
    }

    Ok(())
}

fn deploy_rollback(
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<(), String> {
    let config = load_config(host, user, path, service)?;

    println!("  {} Rolling back {}...", "↩️".yellow(), config.service);

    // Restore backup
    ssh(
        &config,
        &format!(
            "cp {}/{}.bak {}/{}",
            config.path, config.binary, config.path, config.binary
        ),
    )?;

    // Restart
    ssh(&config, &format!("systemctl restart {}", config.service))?;

    println!("  {} Rolled back to previous version", "✅".green());
    Ok(())
}

// ── Helpers ──

fn load_config(
    host: Option<&str>,
    user: Option<&str>,
    path: Option<&str>,
    service: Option<&str>,
) -> Result<DeployConfig, String> {
    let package = read_package_name().unwrap_or_else(|| "app".into());

    // Try config file first
    if let Ok(content) = fs::read_to_string(CONFIG_FILE) {
        let host = host
            .map(|s| s.to_string())
            .or_else(|| extract_toml(&content, "host"))
            .ok_or("host required — use --host or .vil-deploy.toml")?;
        let user = user
            .map(|s| s.to_string())
            .or_else(|| extract_toml(&content, "user"))
            .unwrap_or_else(|| "root".into());
        let path = path
            .map(|s| s.to_string())
            .or_else(|| extract_toml(&content, "path"))
            .unwrap_or_else(|| format!("/opt/{}", &package));
        let service = service
            .map(|s| s.to_string())
            .or_else(|| extract_toml(&content, "service"))
            .unwrap_or_else(|| package.clone());
        let binary = extract_toml(&content, "binary").unwrap_or_else(|| package.clone());
        let health_url = extract_toml(&content, "url");

        return Ok(DeployConfig {
            host,
            user,
            path,
            service,
            binary,
            health_url,
        });
    }

    // CLI args only
    let host = host.ok_or("host required — use --host or run `vil deploy init`")?;
    Ok(DeployConfig {
        host: host.to_string(),
        user: user.unwrap_or("root").to_string(),
        path: path.unwrap_or(&format!("/opt/{}", &package)).to_string(),
        service: service.unwrap_or(&package).to_string(),
        binary: package,
        health_url: None,
    })
}

fn ssh(config: &DeployConfig, cmd: &str) -> Result<String, String> {
    let output = Command::new("ssh")
        .args([
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            "ConnectTimeout=10",
            &format!("{}@{}", config.user, config.host),
            cmd,
        ])
        .output()
        .map_err(|e| format!("ssh: {}", e))?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        let err = String::from_utf8_lossy(&output.stderr).to_string();
        Err(format!("ssh error: {}", err.trim()))
    }
}

fn scp(local_path: &str, config: &DeployConfig) -> Result<(), String> {
    let remote = format!(
        "{}@{}:{}/{}",
        config.user, config.host, config.path, config.binary
    );
    let status = Command::new("scp")
        .args(["-o", "StrictHostKeyChecking=no", local_path, &remote])
        .status()
        .map_err(|e| format!("scp: {}", e))?;

    if status.success() {
        // Make executable
        ssh(
            config,
            &format!("chmod +x {}/{}", config.path, config.binary),
        )?;
        Ok(())
    } else {
        Err("scp failed".into())
    }
}

fn extract_toml(content: &str, key: &str) -> Option<String> {
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(key) && trimmed.contains('=') {
            if let Some(val) = trimmed.split('=').nth(1) {
                return Some(val.trim().trim_matches('"').to_string());
            }
        }
    }
    None
}

fn read_package_name() -> Option<String> {
    let content = std::fs::read_to_string("Cargo.toml").ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("name") {
            if let Some(val) = trimmed.split('=').nth(1) {
                return Some(val.trim().trim_matches('"').to_string());
            }
        }
    }
    None
}
